name: ktp_scanner_app
description: "A new Flutter project for KTP Scanning and Processing."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  #Live Camera & Image Capture
  camera: ^0.12.1
  # UI & Icons
  cupertino_icons: ^1.0.8

  # Image & Camera Processing
  image_picker: ^1.2.3
  image: ^4.10.1

  # OCR & Machine Learning
  google_mlkit_text_recognition: ^0.17.1
  tflite_flutter: ^0.12.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Asset folder pendaftaran model YOLO & gambar
  assets:
  - assets/best_float32.tflite
